codeit-sprint4-team9/rolling-paper

- src/App.js
> [이재성] ui작업완료

- package-lock.json
- package.json
- src/App.jsx
- src/App.module.scss
- src/AppRouter.jsx
- src/components/Header/Header.jsx
- src/index.jsx
- src/pages/HomePage/Home.jsx
- src/pages/ListPage/List.jsx
- src/pages/PostPage/EditPage/Edit.jsx
- src/pages/PostPage/MessagePage/Message.jsx
- src/pages/PostPage/NewPost/NewPost.jsx
- src/pages/PostPage/Post.jsx
> [#4] docs: 초기셋팅을 위한 폴더구조 & 라우팅설정(진행중)

- .eslintrc
- src/App.jsx
- src/AppRouter.jsx
> [#4] refactor: 라우팅 수정 완료

- src/utils/classNames.js
- 클래스명을 편리하게 합치기위한 함수 생성
- cn함수 생성
- 클래스명을 입력받아 truthy한 값만 반환
#16
> [#16] feat: 2개 이상의 클래스명을 합쳐서 반환해주는 함수 추가

- package-lock.json
- package.json
- src/styles/_base.scss
- _base.scss파일에서 body태그에 boxsizing border-box
#4
> [#4] docs: Add box-sizing: border-box

- src/components/Badge/Badge.jsx
- src/components/Badge/Badge.module.scss
- src/pages/PostPage/Post.jsx
- 설정한 관계에 따른 배경 글씨 색상이 세팅 되어 있는 badge를 생성
#18
> [#18] feat: 설정한 관계를 표시하는 Badge 생성

- src/components/Input/Input.jsx
- src/components/Input/Input.module.scss
> [#10] feat: Component input

- .eslintrc
- src/AppRouter.jsx
- src/components/Button/DeletedButton.jsx
- src/components/Button/DeletedButton.module.scss
- src/components/Button/OutlinedButton.jsx
- src/components/Button/OutlinedButton.module.scss
- src/constant/constant.js
요약
* Outlined, Deleted Button 분리
* hasIcon에 따라 아이콘 유무 처리
-> hasIcon은 size L, M, S 만 가능 !
-> css에 L, M, S 사이즈는 width 주석처리 해놨어요 ! hasIcon의 유무에 따라 width도 정해지는데 그 조건을 어떻게 해야할지 모르겠어요 ! 근데 L, M, S 사이즈는 무조건 Icon img가 필요해서 일단 주석처리 해놓고 나중에 필요하면 바꿀게요 ???
* Size에 따라 버튼 크기 변경 (extraLarge, large, medium, small)
* isDisabled에 따라 아이콘 이미지 변경
</br>
</br>
</br>
</br>
> [#11]Outlined button

- src/components/Toast/Toast.jsx
- src/components/Toast/Toast.module.scss
- src/constant/constant.js
- 공유시 알림으로 뜨는 Toast 제작
- children으로 보내준 값을 Toast Title로 보여줌.
#35
> [#35] feat: Component toast

- src/components/Bar/Bar.module.scss
- src/components/Button/Button.module.scss
- src/components/Button/DeletedButton.module.scss
- src/components/Button/OutlinedButton.module.scss
- src/components/Button/ToggleButton.module.scss
- src/components/Header/Header.module.scss
- src/components/Modal/Modal.module.scss
- src/components/Profile/Profile.module.scss
- src/components/Profiles/Profiles.module.scss
- src/styles/_mixins.scss
* px 단위 rem으로 수정
* stylelint 사용해서 순서 정리했슴당
> SCSS 전체 파일 단위, 순서 정리

- src/components/Button/ToggleButton.jsx
-  togglebutton handleClick함수에 event.preventDefault() 추가
- form에서 button이 submit역할을 하기 때문에 페이지가 새로고침 되는 현상을 막기위해 event.preventDefault() 추가
#42
> [#42] refactor: togglebutton handleClick함수에 event.preventDefault() 추가

- src/constant/constant.js
- constant변수 절대 경로 변경
- /assets/*.* => assets/*.*
#42
> [#42] refactor: constatn변수 절대 경로 변경

- src/components/Dropdown/Dropdown.module.scss
- 드롭다운 컴포넌트 스타일 추가
- 드롭다운 메뉴 출력시 다른 요소들 밀림 현상 제거를 위한 position, z-index, background추가
#42
> [#42] dropdown component items z-index, background, position 추가

- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.module.scss
> [#52] modal 버튼 수정

- src/styles/_base.scss
- src/styles/_mixins.scss
* base
-> box-sizing: border-box; 중복 제거
* mixins
-> px에서 rem으로 변경
> base, mixins 수정

- package-lock.json
- package.json
- src/constant/constant.js
- src/utils/axios.js
- axios 설치
- baseUrl, ContentType 상수 설정
- axiosCreateInstance함수 생성
- npm install axios
- 상수 설정
```javascript
export const AXIOS_BASE_URL = 'https://rolling-api.vercel.app/4-9/';
export const AXIOS_CONTENT_TYPE = 'application/json';
```
- axiosCreateInstance 함수
```jsx
import axios from 'axios';
import { AXIOS_BASE_URL, AXIOS_CONTENT_TYPE } from '../constant/constant';
const createAxiosInstance = () => {
return axios.create({
baseURL: AXIOS_BASE_URL,
headers: { 'Content-Type': AXIOS_CONTENT_TYPE },
});
};
export default createAxiosInstance;
```
#60
> [#60] feat: axios설치 & BASEURL,CONTENTYPE설정, axiosCreateInstance함수 생성

- src/constant/constant.js
-  constant 이미지 절대 경로로 수정
-constant 이미지 절대 경로로 수정
assets/. => /assets/.
#66
> [#66] fix: constant path 절대 경로로 수정

- src/App.module.css
- src/App.module.scss
- App.module scss의 width, height변경
- App.module.css 제거
- width:100vw -> max-width: 100vw
- height:100vh -> min-height: 100vh
#42
> [#42] refactor: Modify base width, height

- src/components/Input/Input.jsx
- value, onChange 인수 추가
- Input컴포넌트를 사용하는 곳에서 value를 사용할수 있도록 인수 추가
#42
> [#42] refactor: Input 컴포넌트 인수 추가(value, onChange)

- src/constant/constant.js
-머지 후 constant 중복으로 인한 중복제거
아래 두개 중복내용 삭제했습니다
##이슈 번호
#81
> [#81 ]fix : constant 중복 내용에 대하여 삭제

- public/assets/enabled.svg
- src/pages/PostPage/NewPost/NewPost.jsx
- src/pages/PostPage/NewPost/NewPost.module.scss
- src/pages/PostPage/NewPost/OptionCard/OptionCard.jsx
- src/pages/PostPage/NewPost/OptionCard/OptionCard.module.scss
- src/pages/PostPage/NewPost/OptionCard/enabled.svg
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.jsx
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.module.scss
- PostPage Layout 생성
- PostPage를 위한 OptionCardList 컴포넌트 생성
- PostPage를 위한 OptionCard 컴포넌트 생성
- PostPage Layout & Components 생성
- enabled.svg 이미지 파일 추가
#75
> [#75] feat: Implement Postpage Layout & Components(OptionCardList, OptionCard)

- public/assets/enabled.svg
- src/components/Input/Input.jsx
- src/constant/constant.js
- src/pages/PostPage/NewPost/NewPost.jsx
- src/pages/PostPage/NewPost/NewPost.module.scss
- src/pages/PostPage/NewPost/OptionCard/OptionCard.jsx
- src/pages/PostPage/NewPost/OptionCard/OptionCard.module.scss
- src/pages/PostPage/NewPost/OptionCard/enabled.svg
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.jsx
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.module.scss
- Input에서 공란으로 focusOut시 Erro 발생
##이슈 번호
#75
> [#75] feat: post page - Input Error 기능 구현

- src/pages/PostPage/MessagePage/FontPicker.jsx
- src/pages/PostPage/MessagePage/InputName.module.scss
- src/pages/PostPage/MessagePage/Message.jsx
- src/pages/PostPage/MessagePage/Message.module.scss
- src/pages/PostPage/MessagePage/ProfileImagePicker.module.scss
- src/pages/PostPage/MessagePage/RelationshipPicker.jsx
- src/pages/PostPage/MessagePage/TextAreaEditor.module.scss
- src/pages/PostPage/MessagePage/_mixins.scss
- message 페이지 버튼 조건에 따른 활성화 비활성화 변경 및 메세지 컴포넌트로 데이터 업데이트
- profileImagePicker컴포넌트에는 onChange이벤트 미적용
- 데이터 업데이트 여부
- 입력값이 없을 때
- 조건을 충족하였을 때
입력과 텍스트가 입력되었을때
closes #83
> [#83 ] message 페이지 버튼 조건에 따른 활성화 비활성화 변경 및 메세지 컴포넌트로 데이터 업데이트

- src/components/Dropdown/Dropdown.jsx
- src/constant/constant.js
- src/pages/PostPage/MessagePage/InputName.jsx
- constant.js 파일 폰트명  pretendar 👉pretendard 오타수정
- dropdwon 컴포넌트에  데이터를 받아오기 위하여 onChange 추가
- input 컴포넌트 변경사항 반영하여 오류 코드 수정
- dropdown 컴포넌트
`const Dropdown = ({ optionList = [], initialOption = null, isDisabled, isError, onChange //추가 }) => {
const [isOpen, setIsOpen] = useState(false);
const [selectedOption, setSelectedOption] = useState(initialOption);
const handleOptionClick = option => {
setSelectedOption(option);
setIsOpen(false);
onChange(option) //추가;
}`
closes #88
> [#88] message 페이지 오류 수정 및 오타 수정

- public/assets/enabled.svg
- src/components/Input/Input.jsx
- src/constant/constant.js
- src/pages/PostPage/NewPost/NewPost.jsx
- src/pages/PostPage/NewPost/NewPost.module.scss
- src/pages/PostPage/NewPost/OptionCard/OptionCard.jsx
- src/pages/PostPage/NewPost/OptionCard/OptionCard.module.scss
- src/pages/PostPage/NewPost/OptionCard/enabled.svg
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.jsx
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.module.scss
- 사용자 선택 배경 업로드 UI 및 미리보기 기능 구현
- 기존 upload UI에서 공통 component버튼으로 배경 업로드 버튼 구현
- URL.createObjectURL 메서드를 사용하여 미리보기 구현
#75
> [#75] feat: Postpage 배경 업로드 UI 및 미리보기 구현

- src/components/Profile/Profile.jsx
- src/components/Profile/Profile.module.scss
- src/components/Profiles/Profiles.jsx
- src/components/Profiles/Profiles.module.scss
[#77] 프로필 그룹화 컴포넌트 수정
- profileList : 객체 형태 프로필 리스트
- size : default = 'small'
-  xSmall : post페이지 상단 bar에서 사용
- small : card컴포넌트에서 사용
`const Profiles = ({ profileList, size = 'small' }) => {`
1. POST페이지에 사용
2. post페이지 상단 bar
> [#77] 프로필 그룹화 컴포넌트 Component-profiles

- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- 레이아웃 
- 버튼 선택 시 포스트로 이동
- 데이터 연결
- 캐러셀 적용
> [#63] list 페이지 레이아웃

- package-lock.json
- package.json
- src/components/Profiles/Profiles.jsx
- src/pages/PostPage/UserPost/Bar/Emoji.jsx
- src/pages/PostPage/UserPost/Bar/Emoji.module.scss
* emoji-picker-react 사용
- EmojiPicker에서 emoji를 누르면 postEmojiData에 선택된 emoji를 전달해서 post 요청
- pickEmoji state 값에 선택된 emoji 저장
- mainEmojiData, emojiData state에 업데이트된 emojiData 전달 후 Badge 리렌더링
- pickEmoji 초기화 (초기화하지않으면 똑같은 이모지 눌렀을 때 리렌더링 안 됨)
```javascript
const postEmojiData = async emojiObject => {
try {
await axiosInstance.post(`/recipients/${id}/reactions/`, {
emoji: `${emojiObject.emoji}`,
type: 'increase',
});
} catch (error) {
console.error('POST 요청 에러:', error);
}
};
const getEmojiData = async (limit = null) => {
const endpoint = limit ? `?limit=${limit}` : '';
try {
const response = await axiosInstance.get(`/recipients/${id}/reactions/${endpoint}`);
return response.data.results;
} catch (error) {
console.log('GET 요청 에러:', error);
}
};
useEffect(() => {
const loadEmojiData = async () …
```
> [#85]Bar-emoji 기능 구현

- src/components/Header/Header.jsx
- src/components/Header/Header.module.scss
> #103 헤더영역 버튼컴포넌트 적용 및 css수정

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.module.scss
- src/components/Profile/Profile.module.scss
- src/pages/PostPage/MessagePage/FontPicker/FontPicker.jsx
- src/pages/PostPage/MessagePage/FontPicker/FontPicker.module.scss
- src/pages/PostPage/MessagePage/Message.jsx
- src/pages/PostPage/MessagePage/Message.module.scss
- src/pages/PostPage/MessagePage/ProfileImagePicker/ProfileImagePicker.jsx
- src/pages/PostPage/MessagePage/ProfileImagePicker/ProfileImagePicker.module.scss
- src/pages/PostPage/MessagePage/TextAreaEditor/TextAreaEditor.jsx
- src/pages/PostPage/MessagePage/TextAreaEditor/TextAreaEditor.module.scss
- src/pages/PostPage/MessagePage/TextAreaEditor/quill.scss
- src/styles/_index.scss
- src/utils/kakao.js
- 메세지 페이지 반응형 적용
- 드롭다운 컴포넌트 수정사항 있습니다
- 프로필  컴포넌트 css 수정사항 있습니다
- 텍스트 에디터 css 적용
- 태블릿 폰트 드롭다운 버튼 밀어내도록 적용
- 모바일 프로필 사이즈 변화 및 두줄로 정렬 폰트 드롭다운 아래 여백 
-텍스트에디터 
closes #109
> [#109 ] message 페이지 반응형 적용

- src/components/Carousel/Carousel.jsx
- src/components/Carousel/Carousel.module.scss
> [#89]refactor: 캐러쉘 컴포넌트 스타일(마진) 조정

- src/hooks/useFetchData.js
- 공통적으로 사용하는 데이터를 가져오는 부분을 커스텀훅 useFetchData 제작
- data, isLoading, isError 반환
- 사용하는 단에서 `const {data, isLoading, isError} = useFetchData(url)` 처럼 사용
```jsx
import { useEffect, useState } from 'react';
import createAxiosInstance from '../utils/axios';
const useFetchData = url => {
const [data, setData] = useState(null);
const [isLoading, setIsLoading] = useState(false);
const [error, setError] = useState(null);
useEffect(() => {
const fetchData = async () => {
setIsLoading(true);
try {
const axios = createAxiosInstance();
const { data: response } = await axios.get(url);
setData(response);
} catch (error) {
setError(error);
} finally {
setIsLoading(false);
}
};
fetchData();
}, [url]);
return { data, isLoading, error };
};
export default useFetchData;
```
#116
> [#116] feat: 커스텀훅(useFetchData) 제작

- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- 데이터 반영
- 캐러셀 적용
- css 일부 수정(paperList div 마진 외 제거)
> [#112] list 페이지 데이터 연동 및 캐러셀 적용

- src/components/Header/Header.module.scss
- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- list페이지 및 연결된 카드 컴포넌트 반응형 적용
**모바일**
-----------
**태블릿**
-----------
**PC**
-----------
> [#113] list페이지 반응형 적용

- src/components/Header/Header.module.scss
헤더 영역 반응형 디자인 적용
** PC **
** 1199px 미만 **
> [#121] header반응형

- src/pages/PostPage/UserPost/CardList/CardList.jsx
- src/utils/kakao.js
refactor: 카카오톡 주석 제거 & 백그라운드 우선순위 변경
> refactor: 카카오톡 주석 제거 & 백그라운드 우선순위 변경

- src/pages/PostPage/UserPost/Bar/Emoji.jsx
* emoji 선택했을 때 EmojiPicker 닫히도록 수정
```javascript
const handleEmojiClick = async emojiObject => {
await postEmojiData(emojiObject);
setPickEmoji(emojiObject.emoji);
setShowPicker(false); // 추가
};
``` 
* emojiData, mainEmojiData 두 개로 분리하지 않고 하나로 합쳐서 mainEmoji 부분 slice 처리
```javascript
{emojiData.slice(0, 3).map(emoji => (
<BadgeEmoji key={emoji.id} emoji={emoji.emoji} count={emoji.count}></BadgeEmoji>
))}
``` 
* loadEmojiData 중복 코드 정리
---
#127
> [#127]Emoji 수정

- src/pages/PostPage/UserPost/Bar/Bar.jsx
- src/pages/PostPage/UserPost/Bar/Bar.module.scss
- src/pages/PostPage/UserPost/Bar/WritingCount.jsx
- src/pages/PostPage/UserPost/Bar/WritingCount.module.scss
- src/pages/PostPage/UserPost/CardList/CardList.jsx
- src/pages/PostPage/UserPost/Post.jsx
- bar컴포넌트의 name, 카운트 구현
- cardlist 컴포넌트의 background 관련 스스로 datafetch -> 데이터 부모 컴포넌트에서 전달로 변경
- post 컴포넌트에서 data를 fetch하여 bar컴포넌트에 name, meesageCount, mesage 전달
- cardList컴포넌트 background 데이터 원래 컴포넌트 내부에서 fetch 해오던것을 post 페이지에서 props로 전달
```jsx
const Post = () => {
const { id } = useParams();
const { data: response, isLoading } = useFetchData(`recipients/${id}/`);
if (isLoading) {
return <div>Ladoing...</div>;
}
if (!response) {
return <div>no Data</div>;
}
const { name, recentMessages, messageCount, backgroundColor, backgroundImageURL } = response;
return (
<div className={css.layout}>
<Bar name={name} messages={recentMessages} messageCount={messageCount} />
<CardList backgroundColor={backgroundColor} backgroundImageURL={backgroundImageURL} />
</div>
);
};
```
#137 #138
> [#137] [#138] feat: bar 컴포넌트 name, 카운트 구현 & cardlist background데이터 전달 형태 변경

- src/components/Badge/BadgeEmoji.module.scss
- src/pages/PostPage/MessagePage/TextAreaEditor/quill.scss
- src/pages/PostPage/MessagePage/_mixins.scss
- src/pages/PostPage/UserPost/Bar/Emoji.module.scss
- emoji badge 크기 수정
- text edtitor 모바일 사이즈 툴바 요소 유지되게 수정
##이슈번호
closes #135
> [#135 ]fix : emoji badge  사이즈 수정 및 text editor 반응형 수정

- src/components/Button/Button.module.scss
- src/components/Button/OutlinedButton.module.scss
- src/components/Button/ToggleButton.module.scss
- src/components/Header/Header.module.scss
- src/pages/PostPage/UserPost/Bar/Share.module.scss
[#144] fix : 헤더 - 반응형 오작동 되는 부분 수정
- 일정 픽셀에서 양쪽 마진이 적용되지 않던 부분 수정
1200정도에서 발생하던 마진이 실종되던 현상 수정하였습니다.
> [#144] fix : 헤더 - 반응형 오작동 되는 부분 수정

- src/components/Modal/Modal.module.scss
- src/pages/PostPage/UserPost/CardList/Card.module.scss
- src/pages/PostPage/UserPost/CardList/CardList.jsx
- src/pages/PostPage/UserPost/CardList/CardList.module.scss
+ post/id 페이지 반응형 UI 구현
+ modal 반응형 UI 구현
+ CardList 저장하기 확인 후 내용 반영 부분 로직 수정 (useEffect 의존성배열 수정)
closed #146
> [#146] post/id 페이지, 모달 반응형 UI 구현

- src/pages/PostPage/UserPost/CardList/Card.module.scss
+ 카드 divider와 textbox 의 width 고정값에서 %값으로 변경
> Refactor: 카드 divider와 textbox  width 반응형 수정

- src/pages/PostPage/NewPost/NewPost.module.scss
- src/pages/PostPage/NewPost/OptionCardList/OptionCardList.module.scss
import meida -> media 로 수정하여 로드오류 고쳤습니다
> Fix: 머지 후 import 오타 수정

- src/pages/PostPage/UserPost/CardList/CardList.jsx
- src/pages/PostPage/UserPost/CardList/CardList.module.scss
+ 편집중일때 + 박스 안보이게 수정
+ 카드리스트 부분 반응형 UI 수정
> Fix: 편집중일때 + 박스 안보이게 수정 및 카드리스트  반응형 UI 수정

- src/styles/_media.scss
- pc 기준 1024px -> 1200px로 변경
##이슈 번호
#149
> [#149] refactor: 반응형 pc 기준 1200px 변경

- src/components/Header/Header.module.scss
- Header 좌측정렬 되어있는것 가운데 정렬
#149
> [#149] refactor: Header 컨텐츠 가운데 정렬

- src/components/Carousel/Carousel.module.scss
- Carousel 반응형 추가
- 1200px 미만에서(tablet, mobile환경) 캐러셀 버튼 제거 슬라이드 기능 활성화
#149
> [#149] Carousel 반응형 추가

- src/components/Carousel/Carousel.module.scss
- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- list페이지 반응형 추가
- 시멘틱 태그 변경 (section, article h2)
- 클래스 네임 변경 (컨벤션 규칙에 맞춰서)
- mobile, tablet 환경에서 카드 컴포넌트 마진 0 적용
- article section h1, h2 적절한 시멘틱태그 변경
- 클래스네임 변경(Area -> layout or box)
#149
> [#149] list페이지 반응형 추가 & 시멘틱 태그변경 & 클래스 네임 변경

- src/components/Carousel/Carousel.module.scss
- src/constant/constant.js
- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- src/pages/PostPage/NewPost/NewPost.jsx
- backgroundimageURL 기존 constant에서 MOCK데이터 사용 -> background-images/에서 fetch
#149
> [#149] refactor: 포스트 페이지 backgroundImageURLLIst 서버에서 받오도록 변경

- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
> [#149] 카드 컴포넌트 흰줄 길이 및 두께 조절

- src/components/Carousel/Carousel.module.scss
- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- 버튼에 마우스 올리면 살짝 설레게 만들었음
#149
> [#149] refactor: carousel 컴포넌트 버튼 hover 디자인 추가

- src/components/Header/Header.jsx
- src/components/Header/Header.module.scss
- src/pages/PostPage/UserPost/Bar/Bar.jsx
- src/pages/PostPage/UserPost/Bar/Bar.module.scss
- src/pages/PostPage/UserPost/Bar/Emoji.jsx
- src/pages/PostPage/UserPost/Bar/Emoji.module.scss
- Bar 컴포넌트 반응형 추가
- tablet 페이지에서 이모지 컴포넌트 텍스트제거
- 모바일페이지에서 상단 헤더 제거
- 공유하기와 이모지 사이에 막대바 생성
#149
> [#149] refactor: Bar 반응형 추가

- src/utils/kakao.js
> refactor: 주석제거

- src/pages/PostPage/UserPost/CardList/CardList.jsx
+ 저장하기 후 2번째 저장 시 수정사항 반영 안되는 오류 해결
> Fix:  카드리스트 부분 저장하기 오류

- src/pages/ListPage/List.jsx
- src/pages/PostPage/UserPost/Bar/Emoji.module.scss
* ListPage '나도 만들어보기' 버튼 Link 추가
* emoji mobile 반응형 추가
> ListPage 나도만들어보기 버튼 Link, emoji mobile 반응형 추가

- src/AppRouter.jsx
- src/components/AutoSearching/AutoSearching.jsx
- src/components/AutoSearching/AutoSearching.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- src/pages/Search/Search.jsx
- src/pages/Search/Search.module.scss
- 롤링페이퍼 검색기능 구현
- 자동 추천 기능 구현
- UI는 아직 더 손봐야함 ㅎㅎ
- UI손볼곳 추가할 기능들 알려주시면 집어넣도록하겠슴돠 오늘은 이만 퇴근해야함.. 졸려요
#149
> [#149] feat: 검색기능 구현 & 자동 추천 기능 구현

- package-lock.json
- package.json
- src/AppRouter.jsx
- src/components/AutoSearching/AutoSearching.jsx
- src/components/AutoSearching/AutoSearching.module.scss
- src/components/Button/Button.jsx
- src/components/Upload/Upload.jsx
- src/pages/ListPage/List.jsx
- src/pages/ListPage/List.module.scss
- src/pages/Search/Search.jsx
- src/pages/Search/Search.module.scss
- src/utils/cloudinary.js
- 나만의 이미지 추가기능 구현
- 아직 UI는 꾸미지 못했고 기능 구현만 해뒀음(졸려서 내일 할 예정) - 피곤 이슈로 PR도 내용이 다 이상함... 언젠가 변경할예정 ㅎ
#149
> [#149] feat: 나만의 이미지 추가기능 구현

- src/pages/ListPage/List.jsx
- src/pages/PostPage/MessagePage/Message.module.scss
- src/pages/PostPage/UserPost/CardList/CardList.module.scss
> Fix: 로딩에러 수정

- src/pages/PostPage/UserPost/Post.jsx
- src/pages/PostPage/UserPost/Skeleton/CardListSkeleton.jsx
- src/pages/PostPage/UserPost/Skeleton/CardListSkeleton.module.scss
- src/pages/PostPage/UserPost/Skeleton/CardSkeleton.jsx
- src/pages/PostPage/UserPost/Skeleton/CardSkeleton.module.scss
- 포스트페이지 데이터 로딩중 스켈레톤 이미지 구현
#149
> [#149] feat: 포스트페이지 스켈레톤 구현

- src/pages/PostPage/UserPost/CardList/CardList.module.scss
> CardList에서 editButtonArea css 수정

- src/pages/PostPage/UserPost/Post.jsx
feat: 포스트페이지에서 없는 id에 접근시 nofound로 리다이렉팅
> feat: 포스트페이지에서 없는 id에 접근시 nofound로 리다이렉팅

- src/pages/ListPage/Card/Card.jsx
- src/pages/ListPage/Card/Card.module.scss
- src/pages/ListPage/List.jsx
- src/pages/ListPage/Skeleton/SkeletonCards.jsx
- src/pages/ListPage/Skeleton/SkeletonCards.module.scss
> refactor: list페이지 스켈레톤 기존 카드컴포넌트에서 스켈레톤 컴포넌트 제작

- src/pages/PostPage/UserPost/Bar/Bar.module.scss
mobile일 때 emojiPicker와 allEmojiBadge 위치 수정
- Bar.module.scss
```javascript
.contents {
...
justify-content: flex-end;
width: 100%;
}
```
> emoji mobile 위치 수정

- src/pages/ListPage/Skeleton/SkeletonCards.jsx
- src/pages/ListPage/Skeleton/SkeletonCards.module.scss
- src/pages/PostPage/UserPost/Skeleton/CardListSkeleton.module.scss
- src/pages/PostPage/UserPost/Skeleton/CardSkeleton.module.scss
> 스켈레톤 수정했슴다. Skeleton fix

- src/pages/PostPage/UserPost/Post.jsx
- src/pages/PostPage/UserPost/Skeleton/BarSkeleton.jsx
- src/pages/PostPage/UserPost/Skeleton/BarSkeleton.module.scss
> feat: bar컴포넌트 스켈레톤 컴포넌트 구현 및 적용

- src/pages/ListPage/Skeleton/SkeletonCards.module.scss
- src/pages/PostPage/UserPost/CardList/CardList.jsx
- src/pages/PostPage/UserPost/Skeleton/CardListSkeleton.module.scss
> refactor: 스켈레톤 컴포넌트 수정

- src/components/Upload/Upload.jsx
- src/components/Upload/Upload.module.scss
- src/pages/PostPage/MessagePage/ProfileImagePicker/ProfileImagePicker.jsx
- src/pages/PostPage/MessagePage/ProfileImagePicker/ProfileImagePicker.module.scss
[#192 ] message 페이지 이미지 추가하기 기능 추가
> [#192 ] message 페이지 이미지 추가하기 기능 추가

- src/pages/PostPage/UserPost/Skeleton/BarSkeleton.module.scss
- src/pages/PostPage/UserPost/Skeleton/CardListSkeleton.module.scss
> refactor: styles-skeleton

- src/components/Badge/BadgeEmoji.module.scss
- src/pages/PostPage/UserPost/Bar/Bar.module.scss
- src/pages/PostPage/UserPost/Bar/Emoji.module.scss
- src/pages/PostPage/UserPost/Bar/Share.module.scss
> refactor: mobile 반응형 수정(Bar)
